### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by ColinScott**
Updates to Ubuntu 15.10 (Wily Werewolf)
Updates to Docker Compose 1.6.2
Uses Mono repo (for Mono obviously)
Changes how dnvm is installed so it works for the vagrant user
Silences curl invocations so their output doesn't spam the vagrant build.

### CODE REVIEW

**Comment by humblelistener** [comment]
I actually removed dnvm from devbox some time back. 
Thinking about it, dnvm should not be needed in devbox. docker images will include them in the build.
I will test the docker & docker compose changes and will accept it.

**Comment by humblelistener** [comment]
It is taking ages to download the vagrant image! not tonight :sleepy:

**Comment by ColinScott** [comment]
The advantage of having dnvm to hand is that you can run the tests in something much closer to what will be used in production (mono on Linux).

**Comment by ColinScott** [comment]
Removed merge conflict but otherwise no other changes.

**Pull request merged**
